services:
  cinema-frontend:
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - "../Front End Angular/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro"
      - /etc/letsencrypt:/etc/letsencrypt:ro

  cinema-backend:
    restart: unless-stopped
    environment:
      SERVER_FORWARD_HEADERS_STRATEGY: framework

  mysql-cinema:
    restart: unless-stopped